sudo: false

language: node_js

node_js:
  - 10
  - 8

before_install:
  - npm install -g npm
  - npm install phantomjs-prebuilt

install:
  - npm install

after_install:
  - npm run build
  - npm test
